# Generated by Django 5.1.1 on 2024-09-29 19:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField()),
                ('source', models.CharField()),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('very_rare', 'Very Rare'), ('legendary', 'Legendary'), ('artifact', 'Artifact')], null=True)),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('name', 'source'), name='api_item_name_source_uniq')],
            },
        ),
    ]
