# Generated by Django 5.1.1 on 2024-11-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='api_item_name_source_uniq',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dndbeyond_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
