# Generated by Django 5.1.1 on 2024-11-24 22:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_source_item_image_url_alter_item_dndbeyond_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('dndbeyond_id', models.CharField(blank=True, null=True, unique=True)),
                ('name', models.CharField()),
                ('race', models.CharField()),
                ('dnd_class', models.CharField()),
                ('level', models.IntegerField()),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('strength_score', models.IntegerField()),
                ('dexterity_score', models.IntegerField()),
                ('constitution_score', models.IntegerField()),
                ('intelligence_score', models.IntegerField()),
                ('wisdom_score', models.IntegerField()),
                ('charisma_score', models.IntegerField()),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
